[package]
name = "gitspy-app"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
gitspy-core = { path = "../crates/gitspy-core" }
gitspy-repo = { path = "../crates/gitspy-repo" }
ts-rs = "12.0.1"
gitspy-exec = { version = "0.1.0", path = "../crates/gitspy-exec" }
notify = "8.2.0"
notify-debouncer-full = "0.7.0"
