import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const target = join(root, 'THIRD-PARTY.md');

const npmPackages = () => {
  const lock = JSON.parse(readFileSync(join(root, 'package-lock.json'), 'utf8'));
  const own = lock.packages[''];
  const wanted = new Set(Object.keys(own.dependencies ?? {}));
  const found = new Map();
  const visit = (name) => {
    const entry = lock.packages[`node_modules/${name}`];
    if (!entry || found.has(name)) return;
    found.set(name, { version: entry.version, license: entry.license ?? 'see package' });
    for (const dep of Object.keys(entry.dependencies ?? {})) visit(dep);
  };
  for (const name of wanted) visit(name);
  return [...found.entries()]
    .map(([name, info]) => ({ name, ...info }))
    .sort((a, b) => a.name.localeCompare(b.name));
};

const cargoCrates = () => {
  const lines = execFileSync(
    'cargo',
    [
      'tree',
      '-p',
      'gitspy-app',
      '-e',
      'normal',
      '--target',
      'all',
      '--prefix',
      'none',
      '--format',
      '{p}|{l}',
    ],
    { cwd: root, encoding: 'utf8' },
  )
    .split('\n')
    .filter(Boolean);
  const own = /^gitspy-/;
  const found = new Map();
  for (const line of lines) {
    const [spec, license] = line.split('|');
    const [name, version] = spec.split(' ');
    if (own.test(name) || found.has(name)) continue;
    found.set(name, { version: version ?? '', license: license || 'see crate' });
  }
  return [...found.entries()]
    .map(([name, info]) => ({ name, ...info }))
    .sort((a, b) => a.name.localeCompare(b.name));
};

const fontLicence = () =>
  readFileSync(join(root, 'node_modules/@fontsource-variable/geist/LICENSE'), 'utf8').trim();

const table = (rows) =>
  ['| Package | Version | Licence |', '| --- | --- | --- |']
    .concat(rows.map((r) => `| ${r.name} | ${r.version} | ${r.license} |`))
    .join('\n');

const npm = npmPackages();
const cargo = cargoCrates();

const text = `# Third-party notices

gitspy is licensed under the AGPL-3.0 (see LICENSE). It bundles the software
below, each under its own licence. This file is generated by
\`node scripts/third-party.mjs\` from package-lock.json and Cargo.lock; the full
licence text of every package is in its source archive as published on npm or
crates.io.

## Fonts

Geist and Geist Mono, © 2024 The Geist Project Authors
(https://github.com/vercel/geist-font), SIL Open Font License 1.1:

\`\`\`
${fontLicence()}
\`\`\`

## npm packages shipped in the interface (${npm.length})

${table(npm)}

## Rust crates linked into the binary (${cargo.length})

${table(cargo)}
`;

if (process.argv.includes('--check')) {
  const current = readFileSync(target, 'utf8');
  if (current !== text) {
    console.error('THIRD-PARTY.md is stale: run node scripts/third-party.mjs');
    process.exit(1);
  }
  console.log(`third-party notices current: ${npm.length} npm packages, ${cargo.length} crates`);
} else {
  writeFileSync(target, text);
  console.log(`THIRD-PARTY.md written: ${npm.length} npm packages, ${cargo.length} crates`);
}
