pub const AVATARS_CHANGED: &str = "avatars:changed";

#[cfg(test)]
use crate::hosts;
#[cfg(test)]
use crate::watcher::Change;

#[cfg(test)]
pub fn frontend_module() -> String {
    format!(
        "// This file was generated by gitspy-app tests. Do not edit this file manually.\n\n\
         export const EVENTS = {{\n  repoChanged: '{}',\n  worktreeChanged: '{}',\n  hostConnected: '{}',\n  hostFailed: '{}',\n  avatarsChanged: '{}',\n}} as const;\n",
        Change::Git.event(),
        Change::WorkingTree.event(),
        hosts::CONNECTED_EVENT,
        hosts::FAILED_EVENT,
        AVATARS_CHANGED,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn event_names_are_written_for_the_frontend() {
        let target = concat!(env!("CARGO_MANIFEST_DIR"), "/../src/generated/events.ts");
        std::fs::write(target, frontend_module())
            .expect("the events file is written next to the boundary types");
    }

    #[test]
    fn every_event_name_has_a_namespace() {
        for line in frontend_module().lines() {
            let Some((_, value)) = line.split_once(": '") else {
                continue;
            };
            assert!(
                value.contains(':'),
                "an event name without a namespace will collide with someone else's: {line}"
            );
        }
    }
}
