import {
  Archive,
  Check,
  TriangleAlert,
  Minus,
  Rows2,
  Rows3,
  Columns2,
  CircleDot,
  CloudDownload,
  Copy,
  Download,
  FolderOpen,
  FolderTree,
  GitBranch,
  GitCommitHorizontal,
  GitPullRequest,
  Cloud,
  Plus,
  RefreshCw,
  CircleUserRound,
  Loader2,
  Lock,
  ArrowDown,
  AlignLeft,
  Pencil,
  Pilcrow,
  ArrowUp,
  MoreHorizontal,
  PanelLeftClose,
  PanelLeftOpen,
  Search,
  Settings,
  Tag,
  Terminal,
  Upload,
  X,
  ChevronRight,
  Folder,
  SquareCheckBig,
  Unlink,
} from 'lucide-react';

export const Icon = {
  branch: GitBranch,
  remote: Cloud,
  worktree: FolderTree,
  stash: Archive,
  tag: Tag,
  pullRequest: GitPullRequest,
  issue: CircleDot,
  commit: GitCommitHorizontal,

  fetch: RefreshCw,
  pull: Download,
  push: Upload,
  clone: CloudDownload,
  terminal: Terminal,

  open: FolderOpen,
  add: Plus,
  close: X,
  search: Search,
  copy: Copy,
  settings: Settings,
  host: CircleUserRound,
  waiting: Loader2,
  private: Lock,
  collapse: PanelLeftClose,
  more: MoreHorizontal,
  up: ArrowUp,
  down: ArrowDown,
  whitespace: Pilcrow,
  wrap: AlignLeft,
  edit: Pencil,
  expand: PanelLeftOpen,
  folder: Folder,
  chevron: ChevronRight,
  current: SquareCheckBig,
  resolve: Check,
  conflict: TriangleAlert,
  remove: Minus,
  diffHunk: Rows3,
  diffInline: Rows2,
  diffSplit: Columns2,
  detached: Unlink,
} as const;

export type IconName = keyof typeof Icon;
