export type { AccountView } from './generated/AccountView';
export type { CloneStepView } from './generated/CloneStepView';
export type { TipView } from './generated/TipView';
export type { PullView } from './generated/PullView';
export type { PullListView } from './generated/PullListView';
export type { PullCardView } from './generated/PullCardView';
export type { ConnectStartView } from './generated/ConnectStartView';
export type { ConnectionView } from './generated/ConnectionView';
export type { TemplateCatalogView } from './generated/TemplateCatalogView';
export type { LicenseView } from './generated/LicenseView';
export type { RepoListingView } from './generated/RepoListingView';
export type { ChangedFileView } from './generated/ChangedFileView';
export type { DiffSides } from './generated/DiffSides';
export type { ErrorView } from './generated/ErrorView';
export type { Operation } from './generated/Operation';
export type { PathOperation } from './generated/PathOperation';
export type { StatusEntryView } from './generated/StatusEntryView';
export type { WorkingTreeView } from './generated/WorkingTreeView';
export type { ConflictFileView } from './generated/ConflictFileView';
export type { FileCommitView } from './generated/FileCommitView';
export type { BlameSpanView } from './generated/BlameSpanView';
export type { OperationOutcome } from './generated/OperationOutcome';
export type { Progress } from './generated/Progress';
export type { RecentRepo } from './generated/RecentRepo';
export type { FoundCommitView } from './generated/FoundCommitView';
export type { RepoPassportView } from './generated/RepoPassportView';
export type { RefKindView as RefKind } from './generated/RefKindView';
export type { RefView } from './generated/RefView';
export type { RemoteView } from './generated/RemoteView';
export type { RepoView } from './generated/RepoView';
export type { RowView } from './generated/RowView';
export type { WindowView } from './generated/WindowView';
export type { WorktreeView } from './generated/WorktreeView';
export type { CommitDraftView } from './generated/CommitDraftView';
export type { AiServerView } from './generated/AiServerView';

export type AiProviderId = 'ollama' | 'lmstudio';

export const NODE_KIND = { normal: 0, merge: 1, root: 2, open: 3 } as const;
export const SEGMENT_KIND = { through: 0, branch: 1, merge: 2, stemUp: 3, stemDown: 4 } as const;
