export type { AccountView } from './generated/AccountView';
export type { CloneStepView } from './generated/CloneStepView';
export type { TipView } from './generated/TipView';
export type { PullView } from './generated/PullView';
export type { PullListView } from './generated/PullListView';
export type { PullCardView } from './generated/PullCardView';
export type { DeviceView } from './generated/DeviceView';
export type { RepoListingView } from './generated/RepoListingView';
export type { ChangedFileView } from './generated/ChangedFileView';
export type { DiffSides } from './generated/DiffSides';
export type { ErrorView } from './generated/ErrorView';
export type { Operation } from './generated/Operation';
export type { PathOperation } from './generated/PathOperation';
export type { StatusEntryView } from './generated/StatusEntryView';
export type { WorkingTreeView } from './generated/WorkingTreeView';
export type { OperationOutcome } from './generated/OperationOutcome';
export type { Progress } from './generated/Progress';
export type { RecentRepo } from './generated/RecentRepo';
export type { RefKindView as RefKind } from './generated/RefKindView';
export type { RefView } from './generated/RefView';
export type { RemoteView } from './generated/RemoteView';
export type { RepoView } from './generated/RepoView';
export type { RowView } from './generated/RowView';
export type { WindowView } from './generated/WindowView';
export type { WorktreeView } from './generated/WorktreeView';

export const NODE_KIND = { normal: 0, merge: 1, root: 2, open: 3 } as const;
export const SEGMENT_KIND = { through: 0, branch: 1, merge: 2 } as const;
